"""Initial tables

Revision ID: 370ed91d0ff5
Revises: c91b83a4a01b
Create Date: 2025-05-26 19:53:42.296149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370ed91d0ff5'
down_revision: Union[str, None] = 'c91b83a4a01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reads_id'), table_name='message_reads')
    op.drop_column('message_reads', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_reads', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_message_reads_id'), 'message_reads', ['id'], unique=False)
    # ### end Alembic commands ###
