"""Initial tables

Revision ID: c91b83a4a01b
Revises: 45e8ab43532d
Create Date: 2025-05-26 14:15:36.450348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c91b83a4a01b'
down_revision: Union[str, None] = '45e8ab43532d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chats_admin_id_fkey'), 'chats', type_='foreignkey')
    op.drop_column('chats', 'admin_id')
    op.add_column('group_members', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'is_admin')
    op.add_column('chats', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chats_admin_id_fkey'), 'chats', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###
