"""Initial tables

Revision ID: e47cb65b866b
Revises:
Create Date: 2025-05-25 17:21:52.736857

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic.op import create_index as Ind
from alembic.op import create_table as T
from sqlalchemy import Column as C
from sqlalchemy import ForeignKeyConstraint as FK
from sqlalchemy import PrimaryKeyConstraint as PK

# revision identifiers, used by Alembic.
revision: str = "e47cb65b866b"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    T(
        "users",
        C("username", sa.String(), nullable=True),
        C("email", sa.String(), nullable=True),
        C("is_admin", sa.Boolean(), nullable=True),
        C("password", sa.String(), nullable=True),
        C("id", sa.Uuid(), nullable=False),
        PK("id"),
    )
    Ind(op.f("ix_users_email"), "users", ["email"], unique=True)
    Ind(op.f("ix_users_id"), "users", ["id"], unique=False)
    Ind(op.f("ix_users_username"), "users", ["username"], unique=True)
    T(
        "chats",
        C("name", sa.String(), nullable=True),
        C("is_group", sa.Boolean(), nullable=True),
        C("admin_id", sa.Uuid(), nullable=True),
        C("id", sa.Uuid(), nullable=False),
        FK(
            ["admin_id"],
            ["users.id"],
        ),
        PK("id"),
    )
    Ind(op.f("ix_chats_id"), "chats", ["id"], unique=False)
    T(
        "tokens",
        C("jti", sa.Uuid(), nullable=False),
        C("user_id", sa.Uuid(), nullable=False),
        C("device_id", sa.String(), nullable=False),
        C("revoked", sa.Boolean(), nullable=True),
        C("expired_time", sa.Integer(), nullable=True),
        FK(["user_id"], ["users.id"], ondelete="CASCADE"),
        PK("jti"),
    )
    T(
        "group_members",
        C("user_id", sa.Uuid(), nullable=False),
        C("chat_id", sa.Uuid(), nullable=False),
        C("id", sa.Uuid(), nullable=False),
        FK(
            ["chat_id"],
            ["chats.id"],
        ),
        FK(
            ["user_id"],
            ["users.id"],
        ),
        PK("user_id", "chat_id", "id"),
    )
    Ind(op.f("ix_group_members_id"), "group_members", ["id"], unique=False)
    T(
        "messages",
        C("chat_id", sa.Uuid(), nullable=True),
        C("sender_id", sa.Uuid(), nullable=True),
        C("text", sa.Text(), nullable=True),
        C("timestamp", sa.DateTime(), nullable=True),
        C("is_read", sa.Boolean(), nullable=True),
        C("id", sa.Uuid(), nullable=False),
        FK(
            ["chat_id"],
            ["chats.id"],
        ),
        FK(
            ["sender_id"],
            ["users.id"],
        ),
        PK("id"),
    )
    Ind(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    T(
        "message_reads",
        C("message_id", sa.Uuid(), nullable=False),
        C("user_id", sa.Uuid(), nullable=False),
        C("read_at", sa.DateTime(), nullable=True),
        C("id", sa.Uuid(), nullable=False),
        FK(
            ["message_id"],
            ["messages.id"],
        ),
        FK(
            ["user_id"],
            ["users.id"],
        ),
        PK("message_id", "user_id", "id"),
    )
    Ind(op.f("ix_message_reads_id"), "message_reads", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_reads_id"), table_name="message_reads")
    op.drop_table("message_reads")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_group_members_id"), table_name="group_members")
    op.drop_table("group_members")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_chats_id"), table_name="chats")
    op.drop_table("chats")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
